//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSSO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToken
    {
        public System.Guid Token { get; set; }
        public System.DateTime LastTime { get; set; }
        public int UserId { get; set; }
        public short ClientId { get; set; }
        public string ClientName { get; set; }
        public bool Enabled { get; set; }
    
        public virtual User Base_User { get; set; }
    }
}
