//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSSO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.User_Token = new HashSet<UserToken>();
        }
    
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Passwd { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Area { get; set; }
        public string Nick_Name { get; set; }
        public string PS_URL { get; set; }
        public string Sign { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<short> User_Type { get; set; }
        public Nullable<System.DateTime> User_Reg_time { get; set; }
        public Nullable<System.DateTime> Login_time { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Login_Count { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
    
        public virtual ICollection<UserToken> User_Token { get; set; }
    }
}
